### PR TITLE
Add a script for CI.

### LINKED ISSUE #3: CI
Emacs の dynamic modules 向けの github action を自作してもよいかもしれない

### PR DESCRIPTION
**Pull request by p-baleine**
closes #3.

### CODE REVIEW

**Comment by xuchunyang** [comment]
Hello, I'm also trying to solve the same issue, any idea why this is happening? I'm using Ubuntu 20.04 in the github action and have tried libstdc++6-amd64-cross and lib32stdc++6.

> Run emacs -Q --batch -L build -f batch-byte-compile jq.el
> 
> In toplevel form:
> jq.el:23:1:Error: Module could not be opened: "/home/runner/work/jq.el/jq.el/build/jq-impl.so", "libstdc++.so.6: cannot open shared object file: No such file or directory"
> 
> https://github.com/xuchunyang/jq.el/runs/1075800262?check_suite_focus=true#step:7:9

Here is my github action file https://github.com/xuchunyang/jq.el/blob/master/.github/workflows/test.yml
- it uses Ubuntu 20.04 otherwise cmake will report CXX20 error
- it uses purcell/setup-emacs, emacs-module.h will be `~/.nix-profile/include/emacs-module.h`

**Comment by p-baleine** [comment]
@xuchunyang 

I could have passed Github Actions with this file.

https://github.com/p-baleine/jq.el/blob/6efac0adb43f8464a40d64c04016621c86810e7b/.github/workflows/test.yml

I want some suggestions if I am wrong but jq.el takes advantage of Emacs Dynamic Modules so your Emacs is required to be built with `-with-modules` option at configuration time and I think that purcell/setup-emacs cannot be used.

Also as I did not use any c++20 features in jq.el, I modified CMakeLists.txt as follows.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7830add..a8c734b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -2,7 +2,7 @@ cmake_minimum_required(VERSION 3.10.0)

 project(jq VERSION 0.0.1)

-set(CMAKE_CXX_STANDARD 20)
+set(CMAKE_CXX_STANDARD 17)
 set(CMAKE_CXX_STANDARD_REQUIRED True)
```

**Comment by xuchunyang** [comment]
> I want some suggestions if I am wrong but jq.el takes advantage of Emacs Dynamic Modules so your Emacs is required to be built with `-with-modules` option at configuration time and I think that purcell/setup-emacs cannot be used.

purcell/setup-emacs supports Dynamic Modules, I believe for Emacs 26.2 or 26.3 and higher, however, it installs emacs-module.h to ~/.nix-profile/include/, and I have already compiled jq-impl successfully with purcell/setup-emacs:

```yaml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        emacs_version:
          - 27.1
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Install emacs-module.h
      run: sudo cp -v $HOME/.nix-profile/include/emacs-module.h /usr/include/
    - name: Build jq-impl
      run: mkdir build && cd build && cmake .. && cmake --build .
```

**Comment by p-baleine** [comment]
> purcell/setup-emacs supports Dynamic Modules

Thank you for your suggestion.

I want to make the current test.yml more simple and I'll try purcell/setup-emacs by basing on your snippet.

**Comment by xuchunyang** [comment]
As I said I encountered this error using purcell/setup-emacs, I don't understand what does it mean, I notice you apt install libtool, is this package related? I'm just guessing  

> Run emacs -Q --batch -L build -f batch-byte-compile jq.el
> 
> In toplevel form:
> jq.el:23:1:Error: Module could not be opened: "/home/runner/work/jq.el/jq.el/build/jq-impl.so", "libstdc++.so.6: cannot open shared object file: No such file or directory"

**Comment by p-baleine** [comment]
I could pass tests with the following workflow file.

https://github.com/p-baleine/jq.el/blob/master/.github/workflows/test.yml

The differences are:
  - On `Link liblzma` step, I add a link to liblzma.so.5
  - On `Byte-compile jq.el` and `Run tests` steps, I specify LD_LIBRARY_PATH.

Also, I updated jq.el to reflect your reddit comments.

https://www.reddit.com/r/emacs/comments/imf6wd/new_package_jqel/g44r58e/?utm_source=reddit&utm_medium=web2x&context=3

Thank you very much!

**Pull request merged**
